<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-T7CF7CF" failures="2" tests="6" name="Test" time="81.634" errors="0" timestamp="03 Oct 2023 02:12:12 GMT">
  <testcase classname="org.healthcare.healthcaretest" name="loginbutton" time="14.954"/>
  <testcase classname="org.healthcare.healthcaretest" name="Searchanyone" time="2.713">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	check the credential expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
check the credential expected [true] but found [false]
at org.healthcare.healthcaretest.Searchanyone(healthcaretest.java:59)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- Searchanyone -->
  <testcase classname="org.healthcare.Loginpage" name="lognemail" time="16.89">
    <failure type="java.lang.AssertionError" message="Invalid curencial expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Invalid curencial expected [true] but found [false]
at org.healthcare.Loginpage.lognemail(Loginpage.java:56)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- lognemail -->
  <testcase classname="org.healthcare.healthcaretest" name="saveblood" time="10.128"/>
  <testcase classname="org.healthcare.healthcaretest" name="saveblood" time="4.012"/>
  <testcase classname="org.healthcare.healthcaretest" name="saveblood" time="4.516"/>
</testsuite> <!-- Test -->
